# Task 1 : Creating Arrays

In [2]:
import numpy as np

In [3]:
arr = np.array([i for i in range (1,11)])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
print(type(arr), arr.size, arr.shape, arr.dtype)

<class 'numpy.ndarray'> 10 (10,) int64


In [5]:
arr2D = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
print(type(arr2D), arr2D.size, arr2D.shape, arr2D.dtype)

<class 'numpy.ndarray'> 9 (3, 3) int64


In [11]:
arr3D = np.array([
    [
        [.1,1.0,10.0],[.2,2.0,20],[.3,3.0,30.0],[.4,4.0,40.0],[.5,5.0,50.0]
    ],
    [
        [.6,6.0,60.0],[.7,7.0,70.0],[.8,8.0,80.0],[.9,9.0,90.0],[1.0,10.0,100.0]
    ],
    [
        [1.1,11.0,110.0],[1.2,12.0,120.0],[1.3,13.0,130.0],[1.4,14.0,140.0],[1.5,15.0,150.0]
    ]
])
arr3D

array([[[1.0e-01, 1.0e+00, 1.0e+01],
        [2.0e-01, 2.0e+00, 2.0e+01],
        [3.0e-01, 3.0e+00, 3.0e+01],
        [4.0e-01, 4.0e+00, 4.0e+01],
        [5.0e-01, 5.0e+00, 5.0e+01]],

       [[6.0e-01, 6.0e+00, 6.0e+01],
        [7.0e-01, 7.0e+00, 7.0e+01],
        [8.0e-01, 8.0e+00, 8.0e+01],
        [9.0e-01, 9.0e+00, 9.0e+01],
        [1.0e+00, 1.0e+01, 1.0e+02]],

       [[1.1e+00, 1.1e+01, 1.1e+02],
        [1.2e+00, 1.2e+01, 1.2e+02],
        [1.3e+00, 1.3e+01, 1.3e+02],
        [1.4e+00, 1.4e+01, 1.4e+02],
        [1.5e+00, 1.5e+01, 1.5e+02]]])

In [14]:
print(type(arr3D), arr3D.shape, arr.size, arr3D.dtype)

<class 'numpy.ndarray'> (3, 5, 3) 10 float64


# Task 2: Array indexing and slicing

In [17]:
data = [10,20,30,40,50,60,70,80,90]
arr = np.array(data)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
arr[0:3:]

array([10, 20, 30])

In [20]:
arr[::2]

array([10, 30, 50, 70, 90])

In [21]:
arr[::-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10])

# Task 3 : Mathematical Operations

In [24]:
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

In [27]:
# x= np.arange(1,20,5)
a

array([12, 15, 16,  2, 16], dtype=int32)

In [28]:
b

array([11,  6, 11,  1, 17], dtype=int32)

In [40]:
result_add=[]
result_sub=[]
result_multiply=[]
result_divide=[]
for i in range (len(a)):
    result_add.append(a[i]+b[i])
    result_sub.append(a[i]-b[i])
    result_multiply.append(a[i]*b[i])
    result_divide.append(a[i]/b[i])

In [41]:
for i in result_add:
    print(i, end=",")
print()
for i in result_sub:
    print(i, end=",")
print()
for i in result_multiply:
    print(i, end=",")
print()
for i in result_divide:
    print(i, end=",")
print()

23,21,27,3,33,
1,9,5,1,-1,
132,90,176,2,272,
1.0909090909090908,2.5,1.4545454545454546,2.0,0.9411764705882353,


In [42]:
dot_product = a@b
dot_product

np.int32(672)

In [53]:
mean = np.mean(a)
median = np.median(a)
standDevi = np.std(a)
vari = np.var(a)
print (mean, median, standDevi, vari)

12.2 15.0 5.30659966456864 28.160000000000004


In [47]:
print("Max:",np.max(b),"index:", np.argmax(b))
print("Min:",np.min(b), "index:", np.argmin(b))

Max: 17 index: 4
Min: 1 index 3


# Task 4: Reshaping and Transporting

In [3]:
arr = np.array([i for i in range (1,13)])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
arr2D = arr.reshape((4,3))
arr2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
arr3D = arr.reshape((2,2,3))
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
arrTranspose = arr2D.transpose()
arrTranspose

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [7]:
print(arrTranspose.shape)

(3, 4)


# Task 5 : Boolean Masking and Filtering

In [8]:
arr = np.random.randint(10,50,15)
arr

array([36, 47, 40, 32, 21, 24, 48, 31, 11, 31, 39, 41, 49, 13, 38],
      dtype=int32)

In [9]:
for ele in filter(lambda x : x>25,arr):
    print (ele)

36
47
40
32
48
31
31
39
41
49
38


In [12]:
for i in range (len(arr)):
    if (arr[i]<30):
        arr[i]=0
arr

array([36, 47, 40, 32,  0,  0, 48, 31,  0, 31, 39, 41, 49,  0, 38],
      dtype=int32)

In [13]:
count=0
for ele in filter(lambda x : x%5==0, arr):
    count+=1
print(count)

5


# Task 6 : Working with built-in functions

In [14]:
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
arrIden = np.eye(4)
arrIden

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
arr = np.random.randint(1,100,20)
arr

array([38,  6, 90, 91, 96, 67, 37, 22, 77, 15, 77, 30, 64, 15, 56, 24, 88,
       91, 26, 14], dtype=int32)

In [19]:
arr.sort()
arr

array([ 6, 14, 15, 15, 22, 24, 26, 30, 37, 38, 56, 64, 67, 77, 77, 88, 90,
       91, 91, 96], dtype=int32)

In [20]:
arr[-1:-6:-1]

array([96, 91, 91, 90, 88], dtype=int32)

# Task 7: Generic

In [34]:
import time

In [48]:
# arr1 = np.random.randint(1,100000,size=(100,100))
t1 = time.time()
arr1 =np.random.rand(100,100)
arr1

array([[0.61413117, 0.06796598, 0.70024426, ..., 0.23310487, 0.99625401,
        0.37135131],
       [0.52176061, 0.23478245, 0.69069472, ..., 0.79560975, 0.52174116,
        0.77234443],
       [0.49892812, 0.89709629, 0.58720835, ..., 0.12047265, 0.22595394,
        0.15499871],
       ...,
       [0.24193501, 0.98482714, 0.30739946, ..., 0.19989438, 0.97479236,
        0.74908626],
       [0.73015444, 0.45270004, 0.23291885, ..., 0.96436648, 0.19608926,
        0.69400955],
       [0.39761969, 0.64391561, 0.42645579, ..., 0.32308976, 0.08523076,
        0.64286663]], shape=(100, 100))

In [49]:
arr2=np.random.rand(100,100)
arr2

array([[0.44730188, 0.33790015, 0.60119933, ..., 0.02249394, 0.11755839,
        0.26999761],
       [0.45014654, 0.16378939, 0.93942454, ..., 0.53873516, 0.53491916,
        0.49942469],
       [0.06808578, 0.33702769, 0.51761977, ..., 0.46221956, 0.65383147,
        0.86466423],
       ...,
       [0.68758706, 0.51230664, 0.92135063, ..., 0.40326143, 0.59486527,
        0.25577969],
       [0.68544055, 0.77505461, 0.90098085, ..., 0.6958047 , 0.26156233,
        0.62834791],
       [0.36294948, 0.79048075, 0.59674041, ..., 0.48897195, 0.54805798,
        0.97322352]], shape=(100, 100))

In [50]:
arr3 = arr1 @ arr2
arr3

array([[24.52497351, 25.67588868, 22.14684141, ..., 25.04802555,
        25.66621221, 25.05329393],
       [24.66832349, 25.66112763, 26.81847033, ..., 25.67313922,
        28.05614737, 24.945449  ],
       [22.74091236, 24.41599285, 22.2614764 , ..., 25.19295574,
        25.01533209, 23.44523412],
       ...,
       [22.57362149, 24.73683103, 22.8942791 , ..., 24.72736888,
        23.58966639, 23.33361777],
       [26.61989784, 26.46918011, 25.91791877, ..., 28.37538418,
        28.28167857, 26.05148535],
       [23.9352966 , 22.85297423, 23.41299297, ..., 24.78885534,
        26.60410138, 23.48633127]], shape=(100, 100))

In [51]:
detr = np.linalg.det(arr3)
detr

np.float64(1.2554177647831973e+50)

In [52]:
inv = np.linalg.inv(arr3)
inv

array([[  13.55801468,   -2.30160167,  -63.53182419, ...,   71.81147705,
         -24.54672407, -124.00100163],
       [ -13.48757573,   -4.12968116,   28.56378581, ...,  -28.56255266,
           8.64221819,   58.82682582],
       [   9.49261899,    1.69263151,  -27.58418435, ...,   29.34462593,
          -9.45321573,  -55.15841041],
       ...,
       [  10.01852331,    1.56426584,  -31.51641779, ...,   33.97668642,
         -11.42364776,  -64.11318413],
       [  11.74591678,    3.0935509 ,  -31.37067014, ...,   33.14593433,
         -10.58298801,  -63.7068433 ],
       [  13.95042455,    1.53855507,  -42.19452663, ...,   45.32579253,
         -14.49513708,  -84.06857979]], shape=(100, 100))

In [53]:
t2 = time.time()

In [54]:
execution_Time =  t2-t1
print(execution_Time)

0.9908649921417236
